config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "posts#index"
   #get "posts/top" => "posts#top"
  
  resources :users, only: [:show]


  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
   #フォローとフォローを外すアクション

  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
   #フォロー・フォロワーの一覧ページ

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
   #get "posts/index" => "posts#index"
   #get "posts/new" => "posts#new"
   #get "posts/show" => "posts#show"
   #get "posts/edit" => "posts#edit"
   #get "posts/:id" => "posts#show" ,as: "post"
   #get "posts/:id/edit" => "posts#edit" , as:"edit_post"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

    [:title, :image, :number, :price, :tent, :sleep, :lantan, :cook, :other, :about ].each do |v|
        validates v, presence: true
    end

    belongs_to :user

    acts_as_taggable

    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true

  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :validatable
  
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  acts_as_followable
  acts_as_follower

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end


  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        post = Post.find(params[:post_id])
        comment = post.comments.build(comment_params)
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
        end
    end

    private
        def comment_params
            params.require(:comment).permit(:comment)
        end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def home
        
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end
    
  def destroy
   like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
   like.destroy
   redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   
   before_action :authenticate_user!
    

    def index
        posts = Post.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
        if params[:search] == nil
            @posts= Kaminari.paginate_array(posts).page(params[:page]).per(12)
          elsif params[:search] == ''
            @posts= Kaminari.paginate_array(posts).page(params[:page]).per(12)
          else
            @posted = Post.tagged_with(params[:search], :wild => true, :any => true).includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
            @posts= Kaminari.paginate_array(@posted).page(params[:page]).per(12)
        end
    end

    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
        @tags = Post.tag_counts_on(:tags) 
    end

    def edit
        @post =  Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
            redirect_to :action => "index", :id => post.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])

        if post.user_id == current_user.id
            post.destroy
            redirect_to action: :index
        end
    end

    def new
        @post = Post.new
    end

    def create
        post = Post.new(post_params)

        post.user_id = current_user.id

        if post.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    

    private
    def post_params
        params.require(:post).permit(:tent, :sleep, :lantan, :cook, :other, :title, :advice, :number, :price, :about, :image, :tag_list)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private
  def sheroku open
    et_user
    @user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def show
      @user = User.find(params[:id])
      @posts = @user.posts.page(params[:page]).per(12)
   end

   def follow
      @user = User.find(params[:user_id])
      current_user.follow(@user)
      redirect_to user_path(@user)
   end

   def unfollow
      @user = User.find(params[:user_id])
      current_user.stop_following(@user)
      redirect_to user_path(@user)
   end


   def follow_list
   @user = User.find(params[:user_id])
   end

   def follower_list
   @user = User.find(params[:user_id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homes/home.html.erb
homepage
<%= link_to "log in", posts_top_path %>
<%= link_to "sing up", new_user_registration_path %>

app/views/posts/index.html.erb
<div class="index">
  <div class="search">
    <h3>タグ検索</h3>
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= button_tag(type: "submit", class: "search-btn") do %>
    <svg width="1.3em" height="1.3em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd"
        d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
      <path fill-rule="evenodd"
        d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
    </svg>
    <% end %>
    <% end %>
  </div>
  <br>
  <div class="container">
    <div class="row">
      <% @posts.each do |p| %>
      <div class="post">
        <div class="card bg-dark text-white">
          <%= image_tag p.image_url, class:"card-img" if p.image?%>
          <div class="card-img-overlay">
            <h5 class="card-title"><%= p.title %></h5>
            <p class="card-text"><%= p.number %>人　　　<%= p.price %>yen</p>
            <p class="card-text"><%= p.about %></p>
            <p class="card-text"><a href="/users/<%= p.user.id %>"><%= p.user.name %></a></p>
            <p class="card-text"><% p.tag_list.each do |tag| %>
              <span style="border-radius: 5px;">#<%= tag %></span>
              　 <% end %></p>
          </div>
        </div>
        <br>
        <div class="post-container">
          <% if current_user.already_liked?(p) %>
          <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= p.likes.count %>
          <% end %>
          <% else %>
          <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
          <i class="far fa-heart"></i><%= p.likes.count %>
          <% end %>
          <% end %>
          <%= link_to post_path(p.id) do %>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" />
          </svg>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show">
    <div class="show-post">
        <h3>Post Board</h3>
        <div class="card show-card" style="width: 30rem;">
            <%= image_tag @post.image_url, class:"card-img-top"%>
            <div class="card-body">
                <h5 class="card-title">title：<%= @post.title %></h5>
                <p class="card-text">name：<a href="/users/<%= @post.user.id %>"><%= @post.user.name %></a></p>
                <p class="card-text">人数：<%= @post.number %>人　　金額：<%= @post.price %>yen</p>
                <p class="card-text">about：<%= @post.about %></p>
                <p class="card-text">advice：<%= @post.advice %></p>
                <p class="card-text">投稿日：<%= @post.created_at %></p>
                <p class="card-text"><% @post.tag_list.each do |tag| %>
                    　 <span style="border-radius: 5px;">#<%= tag %></span>
                    <% end %></p>
                <div class="dropdown">
                    <button type="button" id="dropdown1" class="btn btn-secondary dropdown-toggle"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        tools
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdown1">
                        <a class="dropdown-item" href="#">tent：<%= @post.tent %></a>
                        <a class="dropdown-item" href="#">sleeping tool：<%= @post.sleep %></a>
                        <a class="dropdown-item" href="#">lantan：<%= @post.lantan %></a>
                        <a class="dropdown-item" href="#">cooking tool：<%= @post.cook %></a>
                        <a class="dropdown-item" href="#">others：<%= @post.other %></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="icon-button">
            <% if current_user.already_liked?(@post) %>
            <%= link_to post_like_path(@post), method: :delete do %>
            <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
            <% else %>
            <%= link_to post_likes_path(@post), method: :post do %>
            <i class="far fa-heart"></i><%= @post.likes.count %>
            <% end %>
            <% end %>

            
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1">
                いいねしたユーザー
            </button>
            <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="label1">いいねしたユーザー</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <% @post.liked_users.each do |user| %>
                            <li><%= user.name %></li>
                            <% end %>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to edit_post_path(@post.id) do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-brush" fill="cornsilk"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M15.825.12a.5.5 0 0 1 .132.584c-1.53 3.43-4.743 8.17-7.095 10.64a6.067 6.067 0 0 1-2.373 1.534c-.018.227-.06.538-.16.868-.201.659-.667 1.479-1.708 1.74a8.117 8.117 0 0 1-3.078.132 3.658 3.658 0 0 1-.563-.135 1.382 1.382 0 0 1-.465-.247.714.714 0 0 1-.204-.288.622.622 0 0 1 .004-.443c.095-.245.316-.38.461-.452.393-.197.625-.453.867-.826.094-.144.184-.297.287-.472l.117-.198c.151-.255.326-.54.546-.848.528-.739 1.2-.925 1.746-.896.126.007.243.025.348.048.062-.172.142-.38.238-.608.261-.619.658-1.419 1.187-2.069 2.175-2.67 6.18-6.206 9.117-8.104a.5.5 0 0 1 .596.04zM4.705 11.912a1.23 1.23 0 0 0-.419-.1c-.247-.013-.574.05-.88.479a11.01 11.01 0 0 0-.5.777l-.104.177c-.107.181-.213.362-.32.528-.206.317-.438.61-.76.861a7.127 7.127 0 0 0 2.657-.12c.559-.139.843-.569.993-1.06a3.121 3.121 0 0 0 .126-.75l-.793-.792zm1.44.026c.12-.04.277-.1.458-.183a5.068 5.068 0 0 0 1.535-1.1c1.9-1.996 4.412-5.57 6.052-8.631-2.591 1.927-5.566 4.66-7.302 6.792-.442.543-.796 1.243-1.042 1.826a11.507 11.507 0 0 0-.276.721l.575.575zm-4.973 3.04l.007-.005a.031.031 0 0 1-.007.004zm3.582-3.043l.002.001h-.002z" />
        </svg>
        <%end%>
        <%= link_to post_path(@post.id), method: :delete do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="cornsilk"
            xmlns="http://www.w3.org/2000/svg">
            <path
                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
            <path fill-rule="evenodd"
                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
        </svg>
        <%end%>
        <% end %>
    </div>


    <div class="comment-wrapper">
        <p>Comments</p>
        <% @comments.each do |c| %>
        <div class="comment-list">
            <%= c.user.name unless c.user.blank? %>
            :
            <%= c.comment %>
        </div>
        <br>
        <% end %>

        <% if user_signed_in? %>
        <div class="comment-area">
            <%= form_with(model: [@post, @comment], local: true) do |p| %>
            <%= p.text_area :comment %>
            <%= button_tag type: "submit" do %>
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-chat-text" fill="cornsilk"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
                <path fill-rule="evenodd"
                    d="M4 5.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zM4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8zm0 2.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z" />
            </svg>
            <% end %>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br /><br>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="users-show">
  <h2>User page</h2>
  <div class="profile">
    <p>名前 : <%= @user.name %></p>
    <p>プロフィール : <%= @user.profile %></p>

    <div id="follow_form" class="follow">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1">
        follow
      </button>
      <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="label1">following-list</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= @user.follow_count %><br><br>

              <% @user.all_following.each do |user| %>
              ・<%= link_to user.name, user_path(user) %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
            </div>
          </div>
        </div>
      </div>


      <button type="button" class="btn btn-primary follower" data-toggle="modal" data-target="#modal2">
        follower
      </button>
      <div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="label2" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="label2">follower-list</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= @user.followers_count %><br><br>
              <% @user.followers.each do |user| %>
              <%= link_to user.name , user_path(user) %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
            </div>
          </div>
        </div>
      </div>

      <% if current_user.id == @user.id %>
      <%= link_to edit_user_registration_path do %>
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-brush" fill="cornsilk"
        xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M15.825.12a.5.5 0 0 1 .132.584c-1.53 3.43-4.743 8.17-7.095 10.64a6.067 6.067 0 0 1-2.373 1.534c-.018.227-.06.538-.16.868-.201.659-.667 1.479-1.708 1.74a8.117 8.117 0 0 1-3.078.132 3.658 3.658 0 0 1-.563-.135 1.382 1.382 0 0 1-.465-.247.714.714 0 0 1-.204-.288.622.622 0 0 1 .004-.443c.095-.245.316-.38.461-.452.393-.197.625-.453.867-.826.094-.144.184-.297.287-.472l.117-.198c.151-.255.326-.54.546-.848.528-.739 1.2-.925 1.746-.896.126.007.243.025.348.048.062-.172.142-.38.238-.608.261-.619.658-1.419 1.187-2.069 2.175-2.67 6.18-6.206 9.117-8.104a.5.5 0 0 1 .596.04zM4.705 11.912a1.23 1.23 0 0 0-.419-.1c-.247-.013-.574.05-.88.479a11.01 11.01 0 0 0-.5.777l-.104.177c-.107.181-.213.362-.32.528-.206.317-.438.61-.76.861a7.127 7.127 0 0 0 2.657-.12c.559-.139.843-.569.993-1.06a3.121 3.121 0 0 0 .126-.75l-.793-.792zm1.44.026c.12-.04.277-.1.458-.183a5.068 5.068 0 0 0 1.535-1.1c1.9-1.996 4.412-5.57 6.052-8.631-2.591 1.927-5.566 4.66-7.302 6.792-.442.543-.796 1.243-1.042 1.826a11.507 11.507 0 0 0-.276.721l.575.575zm-4.973 3.04l.007-.005a.031.031 0 0 1-.007.004zm3.582-3.043l.002.001h-.002z" />
      </svg>
      <%end%>
      <%= link_to "Logout", destroy_user_session_path, method: :delete , :style=>"color:cornsilk", class:"logout"%>
      <% else %>
      <% if current_user.following? @user %>
      <%= link_to "フォロー中", {controller: :users,action: :unfollow,user_id: @user.id}, method: :put %>
      <% else %>
      <%= link_to "フォローする", {controller: :users,action: :follow,user_id: @user.id}, method: :put %>
      <% end %>
      <%end%>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <% @posts.each do |p| %>
      <div class="post">
        <div class="card bg-dark text-white">
          <%= image_tag p.image_url, class:"card-img" %>
          <div class="card-img-overlay">
            <h5 class="card-title"><%= p.title %></h5>
            <p class="card-text"><%= p.number %>人　　　<%= p.price %>yen</p>
            <p class="card-text"><%= p.about %></p>
            <p class="card-text"><% p.tag_list.each do |tag| %>
              <span style="border-radius: 5px;">#<%= tag %></span>
              　 <% end %></p>
          </div>
        </div>
        <br>
        <div class="post-container">
          <% if current_user.already_liked?(p) %>
          <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= p.likes.count %>
          <% end %>
          <% else %>
          <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
          <i class="far fa-heart"></i><%= p.likes.count %>
          <% end %>
          <% end %>
          <%= link_to post_path(p.id) do %>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" />
          </svg>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>